dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

delete-appointment:
    path: /delete-appointment/{id}
    controller: App\Controller\DashboardController::deleteAppointment
    defaults:
        id: ''

homepage:
    path: /
    controller: App\Controller\BookingController::index

book-appointment:
    path: /book-appointment
    controller: App\Controller\BookingController::bookAppointment

add-appointment:
    path: /add-appointment
    controller: App\Controller\BookingController::addAppointment

fetch-appointment-days:
    path: /fetch-appointment-days
    controller: App\Controller\BookingController::fetchAppointmentDays
